### ISSUE TITLE
Extension makes all files save to Downloads

### ISSUE THREAD

**Issue by Patashu** [colin-c/image-extension-fix#2]
For example, if my last file was saved to Pictures, and I right click -> save as a picture, it will offer to save it to Downloads.

As soon as I turn off the extension it will offer to save to Pictures again, so I know it's specifically the extension at fault.

Experienced on Windows 10 with latest Chrome.

**Comment by colin-c** [comment]
Unfortunately this is a limitation of the Chrome API.

Adding a button to the extension that will allow you to toggle it on or off is planned.
I know this isn't as convenient but it's better than having to disable/enable the extension.

**Comment by colin-c** [comment]
Will revisit this later if the Chrome API changes. Closing for now.

**Comment by User486375** [comment]
Hey, any updates on this issue?
